
// This file was auto-generated by ML.NET Model Builder. 

using AnimalSpotterAi_ConsoleAppwer;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\ruben\Documents\wildcam ai\aangedrukt\PTDC0001.JPG");
AnimalSpotterAi.ModelInput sampleData = new AnimalSpotterAi.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = AnimalSpotterAi.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
